var ENEMY_STATS = {
	B17: {
		HEALTH: 1000,
		BOMB_DAMAGE: 800,
		BOMB_CARPET_SIZE: 5, 
		BOMB_DELAY: 25,
		BOMB_CARPET_COOLDOWN: 200,
		BOMB_EXPLOSION_RADIUS: 100,
		CLIMB_SPEED: 1,
		DESCEND_SPEED: 1
	},
	SHERMAN: {
		HEALTH: 1600,
		DAMAGE: 3,
		BULLET_BURST_SIZE: 6,
		BULLET_DELAY: 3,
		BULLET_BURST_COOLDOWN: 100
	},
	MUSTANG: {
		HEALTH: 400,
		DAMAGE: 10,
		BULLET_BURST_SIZE: 5,
		BULLET_DELAY: 3,
		BULLET_BURST_COOLDOWN: 50,
		CLIMB_SPEED: 2,
		DESCEND_SPEED: 2
	},
	SPITFIRE: {
		HEALTH: 300,
		DAMAGE: 6,
		BULLET_BURST_SIZE: 5,
		BULLET_DELAY: 3,
		BULLET_BURST_COOLDOWN: 40,
		CLIMB_SPEED: 2,
		DESCEND_SPEED: 2
	},
	SOLDIER: {
		HEALTH: 50,
		DAMAGE: 3,
		BULLET_COOLDOWN: 200
	}
};