var PLANE_STATS = {
	BF109: {
		DAMAGE: 60,
		HEALTH: 1200,
		MAX_SPEED: 3,
		CLIMB_SPEED: 7,
		DESCEND_SPEED: 7,
		MACHINEGUN_HEATING: 2,
		MAX_MACHINEGUN_HEAT: 100,
		BOMB_COOLDOWN: 200,
		BOMB_DELAY: 20,
		MAX_BOMBS: 2,
		BOMB_EXPLOSION_RADIUS: 50
	},
	STUKA: {
		DAMAGE: 90,
		HEALTH: 2000,
		MAX_SPEED: 2,
		CLIMB_SPEED: 5,
		DESCEND_SPEED: 15,
		MACHINEGUN_HEATING: 3,
		MAX_MACHINEGUN_HEAT: 250,
		BOMB_COOLDOWN: 100,
		BOMB_DELAY: 10,
		MAX_BOMBS: 4,
		BOMB_EXPLOSION_RADIUS: 70
	},
	KI84: {
		DAMAGE: 120,
		HEALTH: 800,
		MAX_SPEED: 4,
		CLIMB_SPEED: 15,
		DESCEND_SPEED: 5,
		MACHINEGUN_HEATING: 2,
		MAX_MACHINEGUN_HEAT: 80,
		BOMB_COOLDOWN: 250,
		BOMB_DELAY: 20,
		MAX_BOMBS: 1,
		BOMB_EXPLOSION_RADIUS: 60
	}
};
